port: 3001
elastic:
  host: 'localhost:9200'
  usersIndex: 'user'
  usersType: 'user'
  vacanciesIndex: 'vacancy'
  vacanciesType: 'vacancy'
  skillsIndex: 'skill'
  skillsType: 'skill'
  desirableJobsIndex: 'desirablejob'
  desirableJobsType: 'desirablejob'
  desirableTrainingsIndex: 'desirabletraining'
  desirableTrainingsType: 'desirabletraining'
  desirableTrainingLocationsIndex: 'desirabletraininglocation'
  desirableTrainingLocationsType: 'desirabletraininglocation'
  libIndex: 'location'
  locationType: 'location'
  educationTypesIndex: 'educationtype'
  educationTypesType: 'educationType'
  educationLevelIndex: 'educationlevel'
  educationLevelType: 'educationLevel'
  formalEducationLevelIndex: 'formaleducationlevel'
  formalEducationLevelType: 'formalEducationLevel'
  languagesIndex: 'languages'
  languagesType: 'languages'
